name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNGY4OWM4NTMtN2UyZS00ZTJhLWEyZDQtZTI0ZjhjMGNkM2MwIiwidGVuYW50X2lkIjoiYWVhMzM4OTE1NjE0MDAxNDI0ZmM2ZmRlYmEyZWNlMDc1YTczNGE3MDkzZmI4ZWE3NmRmNDE5M2MzY2RlZTAzZSIsImludGVybmFsX3NlY3JldCI6IjM5NmQ1OTAyLTBjZWUtNGMzZi1iY2M4LTU5ZTUzNDJjOWY3MSJ9.FhoPrkJl0_VK1pfTaz7v8BftI7JSVhww7BGcTNACCjE"

JWT_SECRET = "kunjdave"

GOOGLE_CLIENT_ID="692832899029-na2s7coc6g58j0s2a2i1f1oc1sjoa8u6.apps.googleusercontent.com"

GOOGLE_CLIENT_SECRET="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"
